debug_mode: true
discord:
  embed_color: 65280
  enabled: true
  mention_role_id: 'role_id'
  webhook_url: 'webhook_url'
log_level: INFO
notifications:
  intervals:
  - 86400
  - 43200
  - 21600
  - 7200
  - 3600
  - 1800
  - 300
  - 60
  - 30
proxy:
  enabled: true
  max_retries: 3
  proxies:
   - "http://username:password@proxy1.example.com:8080"
   - "http://username:password@proxy2.example.com:8080"
  rotation_enabled: true
  timeout: 10
snipe:
  # Bearer tokens for authentication
  bearer_token: "bearer_token"
 
  # Performance settings (optimized for your Oracle VPS)
  concurrent_requests: 40
  max_snipe_attempts: 3000
  request_delay_ms: 8
  start_sniping_at_seconds: 0
  
  # Rate limiting settings
  max_backoff_seconds: 5
  adaptive_delays: true
  per_token_rate_limiting: true
