debug_mode: true
discord:
  embed_color: 65280
  enabled: true
  mention_role_id: 'Mention_Role_ID'
  webhook_url: 'Webhook_url'
log_level: INFO
notifications:
  intervals:
  - 86400
  - 43200
  - 21600
  - 7200
  - 3600
  - 1800
  - 300
  - 60
  - 30
proxy:
  enabled: true
  max_retries: 3
  proxies:
    - "http://username:password@proxy1.example.com:8080"
    - "http://username:password@proxy2.example.com:8080"
  rotation_enabled: true
  timeout: 10
snipe:
  bearer_token: 'Bearer_Token'
  max_snipe_attempts: 100
  request_delay_ms: 25
  start_sniping_at_seconds: 30

  target_username: 'Target_Username'
